In [2]:
!mkdir coupe
!mkdir deportivos
!mkdir pickup
!mkdir camioneta
!mkdir sedan

mkdir: cannot create directory ‘coupe’: File exists
mkdir: cannot create directory ‘deportivos’: File exists
mkdir: cannot create directory ‘pickup’: File exists
mkdir: cannot create directory ‘camioneta’: File exists
mkdir: cannot create directory ‘sedan’: File exists


In [3]:
%cd coupe
!unzip coupes.zip
%cd ..

%cd camioneta
!unzip camionetas.zip
%cd ..

%cd sedan
!unzip sedanes.zip
%cd ..

%cd pickup
!unzip pickups.zip
%cd ..

%cd deportivos
!unzip deportivos.zip
%cd ..

/content/coupe
Archive:  coupes.zip
  inflating: 0fc654_comprar20un20coupe20ocasion.jpg  
  inflating: 14cb04e0-0150-4b6c-99e2-e333f7b78e4d.png  
  inflating: 17_accord_coupe_008-670x377.jpg  
  inflating: 1-audi-rs5-coupe-2020-fd-hero-front.jpg  
  inflating: 1-bmw-m4-competition-2021-rt-hero-front.jpg  
  inflating: 2017-Aston-Martin-Vantage-V8-coupe-onroad_400_thb.jpg  
  inflating: 2017-Infiniti-Q60-coupe_400_thb.jpg  
  inflating: 2018_Infiniti_Q60_Leonberg_IMG_0156.jpg  
  inflating: 2019_audi_tt_coupe_20-tfsi-quattro_fq_oem_1_1600.jpeg  
  inflating: 2019_audi_tt-rs_f34_fd_410191_600.jpg  
  inflating: 20191210-coupe-05.jpg   
  inflating: 2020-Honda-Civic-Si-Coupe.jpg  
  inflating: 2021_bmw_m2-pic-4749573566737825970-1024x768.jpeg  
  inflating: 2021-GR-Supra-2.0_006-scaled-e1638565017785.jpg  
  inflating: 2022-chevrolet-camaro-zl1-coupe-angular-front.png  
  inflating: 2022-Subaru-BRZ.jpg     
  inflating: 2022-subaru-brz-43-1630281608.jpg  
  inflating: 408620.jpg          

In [6]:
!ls /content/deportivos | wc -l
!ls /content/sedan/ | wc -l
!ls /content/coupe | wc -l
!ls /content/camioneta | wc -l
!ls /content/pickup | wc -l 
 

532
501
474
527
540


In [7]:
!mkdir dataset
!mkdir dataset/deportivos
!mkdir dataset/sedanes
!mkdir dataset/coupe
!mkdir dataset/camionetas
!mkdir dataset/pickups

In [12]:
import shutil
import os
carpeta_fuente = '/content/deportivo'
carpeta_destino = '/content/dataset/deportivos'

def cambio_de_carpeta(carpeta_fuente,carpeta_destino):
  imagenes = os.listdir(carpeta_fuente)

  for i, nombreimg in enumerate(imagenes):
    if i < 474:
      shutil.copy(carpeta_fuente + '/' + nombreimg, carpeta_destino + '/' + nombreimg)

In [14]:
carpeta_fuente = '/content/camioneta'
carpeta_destino = '/content/dataset/camionetas'
cambio_de_carpeta(carpeta_fuente,carpeta_destino)

carpeta_fuente = '/content/coupe'
carpeta_destino = '/content/dataset/coupe'
cambio_de_carpeta(carpeta_fuente,carpeta_destino)

carpeta_fuente = '/content/pickup'
carpeta_destino = '/content/dataset/pickups'
cambio_de_carpeta(carpeta_fuente,carpeta_destino)

carpeta_fuente = '/content/sedan'
carpeta_destino = '/content/dataset/sedanes'
cambio_de_carpeta(carpeta_fuente,carpeta_destino)

In [19]:

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

data_gen = ImageDataGenerator(
    rescale=1. / 255,
    rotation_range = 30,
    width_shift_range = 0.25,
    height_shift_range = 0.25,
    shear_range = 15,
    zoom_range = [0.5, 1.5],
    validation_split=0.2
    
)


In [28]:
x_train = data_gen.flow_from_directory('/content/dataset', target_size = (224,224),
                                                     batch_size = 32, shuffle = True, subset = 'training')

x_test = data_gen.flow_from_directory('/content/dataset', target_size = (224,224),
                                                     batch_size = 32, shuffle = True, subset = 'validation')


Found 1895 images belonging to 5 classes.
Found 470 images belonging to 5 classes.


In [29]:
import tensorflow as tf
import tensorflow_hub as hub
url = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"
mobilnet = hub.KerasLayer(url, input_shape = (224,224,3))



In [30]:
mobilnet.trainable = False


In [32]:
model_hackton = tf.keras.Sequential([mobilnet,tf.keras.layers.Dense(5, activation = 'softmax')
                                     ])

In [36]:
model_hackton.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']  

)

In [37]:
epoch = 50

hsitoria = model_hackton.fit(x_train, epochs = epoch,batch_size= 32,
                             validation_data = x_test,
                  )

Epoch 1/50
21/60 [=========>....................] - ETA: 13s - loss: 1.6964 - accuracy: 0.2768

/usr/local/lib/python3.8/dist-packages/PIL/Image.py:959: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


60/60 [==============================] - 43s 563ms/step - loss: 1.5036 - accuracy: 0.3573 - val_loss: 1.2724 - val_accuracy: 0.4532
Epoch 2/50
60/60 [==============================] - 33s 551ms/step - loss: 1.2717 - accuracy: 0.4544 - val_loss: 1.1789 - val_accuracy: 0.5213
Epoch 3/50
60/60 [==============================] - 34s 560ms/step - loss: 1.1662 - accuracy: 0.5124 - val_loss: 1.1340 - val_accuracy: 0.5426
Epoch 4/50
60/60 [==============================] - 34s 564ms/step - loss: 1.1206 - accuracy: 0.5335 - val_loss: 1.1745 - val_accuracy: 0.5277
Epoch 5/50
60/60 [==============================] - 34s 557ms/step - loss: 1.1175 - accuracy: 0.5293 - val_loss: 1.1129 - val_accuracy: 0.5553
Epoch 6/50
60/60 [==============================] - 33s 558ms/step - loss: 1.0764 - accuracy: 0.5551 - val_loss: 1.0822 - val_accuracy: 0.5511
Epoch 7/50
60/60 [==============================] - 38s 641ms/step - loss: 1.0595 - accuracy: 0.5536 - val_loss: 1.1069 - val_accuracy: 0.5362
Epoch 8/50

In [116]:
model_hackton.save("IA_hackton.h5",hsitoria)
print("modelo creado")

modelo creado


In [110]:
from PIL import Image
import requests
from io import BytesIO
import cv2

def categorizar(url):
  respuesta = requests.get(url)
  img = Image.open(BytesIO(respuesta.content))
  img = np.array(img).astype(float)/255

  img = cv2.resize(img, (224,224))
  prediccion = model_hackton.predict(img.reshape(-1, 224, 224, 3))
  
  
  for i in prediccion[0]:
    if i >ERROR_THRESHOLD:
      bin.append(0)

      return np.argmax(prediccion[0], axis=-1)

    



" print(i)\n  print('_________________________________')\n  print(np.argmax(prediccion[0]))\n  print(np.argmax(prediccion[0], axis=-1))\n  #return np.argmax(prediccion[0], axis=-1)"

In [113]:
categorizar('https://exoticfruitbox.com/wp-content/uploads/2015/10/papaya-3-Exotic.jpg')
categorizar('https://media.revistagq.com/photos/60915663089b2ad8c546730a/master/w_1600%2Cc_limit/bugatti-bolide.jpg')
categorizar('https://www.mitsubishi-motors.com.pe/blog/wp-content/uploads/2018/09/caracteristicas-pick-up-l200-1200x566.jpg')


1/1 [==============================] - 0s 18ms/step
[[0.07399429 0.17239715 0.65853256 0.01613022 0.07894579]]
[0.07399429 0.17239715 0.65853256 0.01613022 0.07894579]
1/1 [==============================] - 0s 18ms/step
[[0.01056815 0.01366783 0.9474432  0.00102749 0.02729334]]
[0.01056815 0.01366783 0.9474432  0.00102749 0.02729334]
1/1 [==============================] - 0s 18ms/step
[[1.3815853e-02 1.2049499e-02 7.9415506e-04 9.6664429e-01 6.6961735e-03]]
[1.3815853e-02 1.2049499e-02 7.9415506e-04 9.6664429e-01 6.6961735e-03]


3

In [111]:
def hacer_prediccion(url):
  prediccion = categorizar(url)
  
  if prediccion == 0 : 
    prediccion = 'camioneta'
  elif prediccion == 1 : 
    prediccion = 'coupe'
  elif prediccion == 2 : 
    prediccion = 'deportivo'
  elif prediccion == 3 : 
    prediccion = 'pickup'
  elif prediccion == 0 : 
    prediccion = 'sedan'
  print(prediccion)
  return prediccion

In [114]:
hacer_prediccion('https://media.revistagq.com/photos/60915663089b2ad8c546730a/master/w_1600%2Cc_limit/bugatti-bolide.jpg')
#0 camionetas
#1 coupe
#2 deportivos
#3 pick up
#4 sedan


1/1 [==============================] - 0s 18ms/step
[[0.01056815 0.01366783 0.9474432  0.00102749 0.02729334]]
[0.01056815 0.01366783 0.9474432  0.00102749 0.02729334]
deportivo


'deportivo'